### ISSUE TITLE
No se puede seleccionar pais Tíbet desde el juego.

### ISSUE THREAD

**Issue by cressidagp** [carky12/EditorPCFutbol2000#2]
### Descripción

Al seleccionar el país Tíbet nos muestra los equipos de China.

### Como reproducir

1. Seleccionar Mercado
2. Luego Ofertas
3. Buscar equipo
4. Asia Oriental
5. Click en el Tíbet

### Versión PC-Fútbol

PC-Fútbol 2000 Extension (drive)

### Hash/commit

-

**Comment by carky12** [comment]
Esto es por que en el paquete de gráficos que hay disponible en PCFMania.com está así, no voy a cambiarlo, y supongo que cuando se hizo el paquete o no había más códigos disponibles para países y a lo mejor aún no era una región con liga independiente de China....no lo sé la verdad, pero como te digo, lo vamos a dejar así....por lo menos por mi parte.

**Comment by cressidagp** [comment]
Pense que era todo obra tuya jajaja. Lo voy a reportar a quien corresponda :D
