### ISSUE TITLE
Ver dorsales y slot al editar equipos.

### ISSUE THREAD

**Issue by cressidagp** [carky12/EditorPCFutbol2000#6]
Hola Carky, creo que ayudaría mucho poder visualizar dichos datos al editar equipo sin tener que entrar para ver jugador por jugador.

![Sin título](https://user-images.githubusercontent.com/63816325/134095305-661588e1-8846-4abb-b50b-efaad43479ab.jpg)

**Comment by carky12** [comment]
Listo, he puesto dos columnas nuevas, la primera para el dorsal y la segunda para el slot. Además he habilitado la ordenación por las columnas Media, Demarcación, Dorsal y Slot. Además he puesto unos botones con imagen para el editar y borrar.

![image](https://user-images.githubusercontent.com/57545449/134310819-88ab0151-2ed6-486e-b718-4fd310e34c77.png)
